languageCode = "en-us"
title = "Brandon Pugh"
baseurl = "http://bpughhugo.netlify.com/"
description= "Brandon Pugh's experiences on professional software development, technology and productivity"
Copyright = "All rights reserved - 2017"
theme = "casper"
enableRobotsTXT = true
[permalinks]
  post = "/blog/:year/:month/:slug/"


[params]
  description = "Condensing fact from the vapor of nuance."
  cover = "images/banner.png"
  author= "Brandon Pugh"
  # authorlocation = "Paris, France"
  authorwebsite = "https://brandonpugh.com"
#   bio= "my bio"
#   logo = "images/logo.png"
  googleAnalyticsUserID = "UA-37923235-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "bpugh"
  twitterName = "brndnpugh"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "brndnpugh"