[context.deploy-preview.environment]
  HUGO_VERSION = "0.88"

[[redirects]]
  from = "/blazor-talk/*"
  to = "https://blazor-talk.netlify.app/:splat"
  status = 200
[[redirects]]  
  from = "/better-way/*"
  to = "https://better-way.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/tdd-talk/*"
  to = "https://tdd-talk.netlify.app/:splat"
  status = 200  
