[context.deploy-preview.environment]
  HUGO_VERSION = "0.121.2"

[[redirects]]
  from = "/blog/:year/:month/:slug"
  to = "/blog/:slug"
  status = 301
[[redirects]]
  from = "/blazor-talk/*"
  to = "https://blazor-talk.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/blazor-talk"
  to = "/blazor-talk/"
  status = 200
[[redirects]]  
  from = "/better-way/*"
  to = "https://better-way.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/tdd-talk/*"
  to = "https://tdd-talk.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/git-talk/*"
  to = "https://git-talk.netlify.app/:splat"
  status = 200
